### ISSUE TITLE
New prototypes for Zone2

### ISSUE THREAD

**Issue by hash99** [stormboy/node-pioneer-avr#4]
Hi,
for testing I cloned your git and added some prototypes for zone2. Is it okay for you to bring it now in your git? If yes, what do you prefer to deal with? I could send it as file directly or I could fork and send you a pull request.
(Only some prototypes as copy of yours like volume to zvolume etc. )

**Comment by stormboy** [comment]
Usually a pull request would be best, but if it's easier send me a patch and I'll have a look.

**Comment by hash99** [comment]
Hi, then I send you a file.
[pioneer-avr.txt](https://github.com/stormboy/node-pioneer-avr/files/2428075/pioneer-avr.txt)

Thank you for your support . 

Regards

**Comment by hash99** [comment]
Hi,
I created a pull request.
